export const adminTokens = {
  colorPrimary: "#1677ff",
  colorInfo: "#0f6cbd",
  colorInfoBg: "#edf6ff",
  colorBgLayout: "#f5f7fb",
  colorBgContainer: "#ffffff",
  colorText: "#172033",
  colorTextSecondary: "rgba(23, 32, 51, 0.56)",
  colorBorder: "#e7ecf3",
  colorSuccess: "#52c41a",
  colorSuccessBg: "#f0f9eb",
  colorWarning: "#faad14",
  colorWarningBg: "#fff8e6",
  colorError: "#ff4d4f",
  colorErrorBg: "#fff1f0",
  borderRadius: 8,
  headerHeight: 56,
  siderWidth: 226,
  siderCollapsedWidth: 64,
  pagePadding: 20,
};
