use_default_settings:
  engines:
    keep_only:
      - baidu

engines:
  - name: baidu
    disabled: false

server:
  secret_key: admin-base-local-search-only
  limiter: false
  image_proxy: false

search:
  safe_search: 1
  formats:
    - html
    - json
