import { Hono } from "hono";
import { success } from "@/lib/response";
import type { HonoVariables } from "@/server/context";
import { ability } from "@/server/middleware/ability";
import { authRequired } from "@/server/middleware/auth";
import { runReadinessChecks } from "@/server/services/readiness-service";
import { aiRoutes } from "./ai";
import { aiAgentRoutes } from "./ai-agent";
import { aiEvalRoutes } from "./ai-eval";
import { aiGovernanceRoutes } from "./ai-governance";
import { aiKnowledgeRoutes } from "./ai-knowledge";
import { aiNotebookRoutes } from "./ai-notebook";
import { aiPricingRoutes } from "./ai-pricing";
import { aiRuntimeRoutes } from "./ai-runtime";
import { aiWebSearchRoutes } from "./ai-web-search";
import { configRoutes } from "./config";
import { dashboardRoutes } from "./dashboard";
import { deptRoutes } from "./dept";
import { dictRoutes } from "./dict";
import { fileRoutes } from "./file";
import { loginLogRoutes } from "./login-log";
import { mailRoutes } from "./mail";
import { moduleGeneratorRoutes } from "./module-generator";
import { noticeRoutes } from "./notice";
import { onlineUserRoutes } from "./online-user";
import { operationLogRoutes } from "./operation-log";
import { oauthProviderRoutes } from "./oauth-provider";
import { profileRoutes } from "./profile";
import { roleRoutes } from "./role";
import { ruleRoutes } from "./rule";
import { settingsRoutes } from "./settings";
import { smsProviderRoutes } from "./sms-provider";
import { smsTemplateRoutes } from "./sms-template";
import { storageRoutes } from "./storage";
import { userRoutes } from "./user";

export const systemRoutes = new Hono<{ Variables: HonoVariables }>();

systemRoutes.get("/doctor", authRequired(), ability("system.config.query"), async (c) => {
  const result = await runReadinessChecks({ includeMail: true });
  return c.json(success(result), result.status === "failed" ? 503 : 200);
});

systemRoutes.route("/", dashboardRoutes);
systemRoutes.route("/", userRoutes);
systemRoutes.route("/", roleRoutes);
systemRoutes.route("/", ruleRoutes);
systemRoutes.route("/", deptRoutes);
systemRoutes.route("/", dictRoutes);
systemRoutes.route("/", settingsRoutes);
systemRoutes.route("/", configRoutes);
systemRoutes.route("/", fileRoutes);
systemRoutes.route("/", aiRoutes);
systemRoutes.route("/", aiAgentRoutes);
systemRoutes.route("/", aiEvalRoutes);
systemRoutes.route("/", aiGovernanceRoutes);
systemRoutes.route("/", aiKnowledgeRoutes);
systemRoutes.route("/", aiNotebookRoutes);
systemRoutes.route("/", aiPricingRoutes);
systemRoutes.route("/", aiRuntimeRoutes);
systemRoutes.route("/", aiWebSearchRoutes);
systemRoutes.route("/", storageRoutes);
systemRoutes.route("/", mailRoutes);
systemRoutes.route("/", moduleGeneratorRoutes);
systemRoutes.route("/", smsProviderRoutes);
systemRoutes.route("/", smsTemplateRoutes);
systemRoutes.route("/", operationLogRoutes);
systemRoutes.route("/", loginLogRoutes);
systemRoutes.route("/", onlineUserRoutes);
systemRoutes.route("/", oauthProviderRoutes);
systemRoutes.route("/", profileRoutes);
systemRoutes.route("/", noticeRoutes);
