import { Hono } from "hono";
import type { HonoVariables } from "@/server/context";
import { configRoutes } from "./config";
import { deptRoutes } from "./dept";
import { dictRoutes } from "./dict";
import { fileRoutes } from "./file";
import { loginLogRoutes } from "./login-log";
import { mailRoutes } from "./mail";
import { noticeRoutes } from "./notice";
import { onlineUserRoutes } from "./online-user";
import { operationLogRoutes } from "./operation-log";
import { profileRoutes } from "./profile";
import { roleRoutes } from "./role";
import { ruleRoutes } from "./rule";
import { storageRoutes } from "./storage";
import { userRoutes } from "./user";

export const systemRoutes = new Hono<{ Variables: HonoVariables }>();

systemRoutes.route("/", userRoutes);
systemRoutes.route("/", roleRoutes);
systemRoutes.route("/", ruleRoutes);
systemRoutes.route("/", deptRoutes);
systemRoutes.route("/", dictRoutes);
systemRoutes.route("/", configRoutes);
systemRoutes.route("/", fileRoutes);
systemRoutes.route("/", storageRoutes);
systemRoutes.route("/", mailRoutes);
systemRoutes.route("/", operationLogRoutes);
systemRoutes.route("/", loginLogRoutes);
systemRoutes.route("/", onlineUserRoutes);
systemRoutes.route("/", profileRoutes);
systemRoutes.route("/", noticeRoutes);
