export type SeedRule = {
  id: number;
  parentId: number;
  type: "menu" | "route" | "nested" | "action";
  key: string;
  name: string;
  path?: string | null;
  icon?: string | null;
  order: number;
  hidden?: number;
};

const moduleRules = [
  {
    route: {
      id: 10,
      parentId: 170,
      key: "system.user",
      name: "用户管理",
      path: "/system/user",
      icon: "user",
      order: 10,
    },
    actions: [
      ["query", "查询用户"],
      ["create", "新增用户"],
      ["update", "编辑用户"],
      ["delete", "删除用户"],
      ["resetPassword", "重置密码"],
    ],
  },
  {
    route: {
      id: 20,
      parentId: 170,
      key: "system.role",
      name: "角色管理",
      path: "/system/role",
      icon: "role",
      order: 20,
    },
    actions: [
      ["query", "查询角色"],
      ["create", "新增角色"],
      ["update", "编辑角色"],
      ["delete", "删除角色"],
      ["setRule", "分配权限"],
      ["status", "切换状态"],
      ["copy", "复制角色"],
    ],
  },
  {
    route: {
      id: 30,
      parentId: 170,
      key: "system.rule",
      name: "菜单权限",
      path: "/system/rule",
      icon: "rule",
      order: 40,
    },
    actions: [
      ["query", "查询菜单"],
      ["create", "新增菜单"],
      ["update", "编辑菜单"],
      ["delete", "删除菜单"],
      ["hidden", "切换显隐"],
      ["status", "切换状态"],
    ],
  },
  {
    route: {
      id: 40,
      parentId: 170,
      key: "system.dept",
      name: "部门管理",
      path: "/system/dept",
      icon: "dept",
      order: 30,
    },
    actions: [
      ["query", "查询部门"],
      ["create", "新增部门"],
      ["update", "编辑部门"],
      ["delete", "删除部门"],
    ],
  },
  {
    route: {
      id: 50,
      parentId: 180,
      key: "system.dict",
      name: "字典管理",
      path: "/system/dict",
      icon: "dict",
      order: 30,
    },
    actions: [
      ["query", "查询字典"],
      ["create", "新增字典"],
      ["update", "编辑字典"],
      ["delete", "删除字典"],
    ],
  },
  {
    route: {
      id: 60,
      parentId: 180,
      key: "system.config",
      name: "高级配置",
      path: "/system/config",
      icon: "config",
      order: 20,
    },
    actions: [
      ["query", "查询配置"],
      ["create", "新增配置"],
      ["update", "编辑配置"],
      ["delete", "删除配置"],
      ["save", "保存配置"],
    ],
  },
  {
    route: {
      id: 150,
      parentId: 180,
      key: "system.settings",
      name: "设置中心",
      path: "/system/settings",
      icon: "settings",
      order: 10,
    },
    actions: [
      ["query", "查看系统设置"],
      ["save", "保存系统设置"],
    ],
  },
  {
    route: {
      id: 70,
      parentId: 2,
      key: "system.file",
      name: "文件管理",
      path: "/system/file",
      icon: "file",
      order: 30,
    },
    actions: [
      ["query", "查询文件"],
      ["upload", "上传文件"],
      ["delete", "删除文件"],
      ["download", "下载文件"],
    ],
  },
  {
    route: {
      id: 80,
      parentId: 180,
      key: "system.storage",
      name: "存储配置",
      path: "/system/storage",
      icon: "storage",
      order: 40,
    },
    actions: [
      ["query", "查询存储"],
      ["create", "新增存储"],
      ["update", "编辑存储"],
      ["delete", "删除存储"],
      ["status", "切换状态"],
      ["setDefault", "设为默认"],
      ["test", "测试连接"],
    ],
  },
  {
    route: {
      id: 90,
      parentId: 180,
      key: "system.mail",
      name: "邮件配置",
      path: "/system/mail/account",
      icon: "mail",
      order: 50,
    },
    actions: [
      ["query", "查询邮件"],
      ["create", "新增邮件"],
      ["update", "编辑邮件"],
      ["delete", "删除邮件"],
      ["status", "切换状态"],
      ["setDefault", "设为默认"],
      ["test", "测试发送"],
    ],
  },
  {
    route: {
      id: 160,
      parentId: 180,
      key: "system.oauthProvider",
      name: "第三方登录",
      path: "/system/oauth/provider",
      icon: "login",
      order: 60,
    },
    actions: [
      ["query", "查询第三方登录"],
      ["create", "新增第三方登录"],
      ["update", "编辑第三方登录"],
      ["delete", "删除第三方登录"],
      ["status", "启停第三方登录"],
      ["test", "测试第三方登录"],
    ],
  },
  {
    route: {
      id: 200,
      parentId: 180,
      key: "system.smsProvider",
      name: "短信配置",
      path: "/system/sms/provider",
      icon: "message",
      order: 70,
    },
    actions: [
      ["query", "查询短信配置"],
      ["create", "新增短信配置"],
      ["update", "编辑短信配置"],
      ["delete", "删除短信配置"],
      ["status", "启停短信配置"],
      ["setDefault", "设为默认短信配置"],
      ["test", "测试短信配置"],
    ],
  },
  {
    route: {
      id: 210,
      parentId: 180,
      key: "system.moduleGenerator",
      name: "模块生成器",
      path: "/system/module/generator",
      icon: "code",
      order: 90,
    },
    actions: [
      ["query", "查看模块生成器"],
      ["generate", "生成模块草稿"],
      ["publish", "发布模块"],
    ],
  },
  {
    route: {
      id: 230,
      parentId: 180,
      key: "system.aiProvider",
      name: "AI Provider",
      path: "/system/ai/provider",
      icon: "api",
      order: 80,
    },
    actions: [
      ["query", "查询 AI Provider"],
      ["create", "新增 AI Provider"],
      ["update", "编辑 AI Provider"],
      ["delete", "删除 AI Provider"],
      ["status", "启停 AI Provider"],
      ["setDefault", "设为默认 AI Provider"],
      ["test", "测试 AI Provider"],
    ],
  },
  {
    route: {
      id: 240,
      parentId: 180,
      key: "system.aiModel",
      name: "AI 模型",
      path: "/system/ai/model",
      icon: "api",
      order: 81,
    },
    actions: [
      ["query", "查询 AI 模型"],
      ["create", "新增 AI 模型"],
      ["update", "编辑 AI 模型"],
      ["delete", "删除 AI 模型"],
      ["status", "启停 AI 模型"],
      ["setDefault", "设为默认 AI 模型"],
      ["test", "测试 AI 模型"],
    ],
  },
  {
    route: {
      id: 100,
      parentId: 190,
      key: "system.operationLog",
      name: "操作日志",
      path: "/system/operation/log",
      icon: "operationLog",
      order: 10,
    },
    actions: [
      ["query", "查询操作日志"],
      ["export", "导出操作日志"],
      ["clean", "清理操作日志"],
    ],
  },
  {
    route: {
      id: 110,
      parentId: 190,
      key: "system.loginLog",
      name: "登录日志",
      path: "/system/login/log",
      icon: "loginLog",
      order: 20,
    },
    actions: [
      ["query", "查询登录日志"],
      ["delete", "删除登录日志"],
      ["clean", "清理登录日志"],
    ],
  },
  {
    route: {
      id: 120,
      parentId: 190,
      key: "system.onlineUser",
      name: "在线用户",
      path: "/system/online/user",
      icon: "onlineUser",
      order: 30,
    },
    actions: [
      ["query", "查询在线用户"],
      ["kick", "强制下线"],
      ["clean", "清理过期会话"],
    ],
  },
  {
    route: {
      id: 130,
      parentId: 2,
      key: "system.notice",
      name: "通知公告",
      path: "/system/notice",
      icon: "notice",
      order: 40,
    },
    actions: [
      ["query", "查询公告"],
      ["create", "新增公告"],
      ["update", "编辑公告"],
      ["delete", "删除公告"],
      ["publish", "发布公告"],
      ["revoke", "撤回公告"],
    ],
  },
  {
    route: {
      id: 220,
      parentId: 180,
      key: "system.smsTemplate",
      name: "短信模板",
      path: "/system/sms/template",
      icon: "message",
      order: 71,
    },
    actions: [
      ["query", "查询短信模板"],
      ["create", "新增短信模板"],
      ["update", "编辑短信模板"],
      ["delete", "删除短信模板"],
      ["status", "启停短信模板"],
      ["test", "测试短信模板"],
    ],
  },
] as const;

export const seedRules: SeedRule[] = [
  {
    id: 1,
    parentId: 0,
    type: "menu",
    key: "dashboard",
    name: "仪表盘",
    icon: "dashboard",
    order: 1,
  },
  {
    id: 3,
    parentId: 1,
    type: "route",
    key: "dashboard.analysis",
    name: "分析页",
    path: "/dashboard",
    icon: "analysis",
    order: 1,
  },
  {
    id: 4,
    parentId: 0,
    type: "menu",
    key: "example",
    name: "示例组件",
    icon: "example",
    order: 5,
  },
  {
    id: 5,
    parentId: 4,
    type: "menu",
    key: "example.table",
    name: "高级表格",
    icon: "table",
    order: 1,
  },
  {
    id: 6,
    parentId: 4,
    type: "menu",
    key: "example.form",
    name: "高级表单",
    icon: "form",
    order: 2,
  },
  {
    id: 2,
    parentId: 0,
    type: "menu",
    key: "system",
    name: "系统管理",
    icon: "system",
    order: 10,
  },
  {
    id: 170,
    parentId: 2,
    type: "menu",
    key: "system.access",
    name: "权限与组织",
    icon: "rule",
    order: 10,
  },
  {
    id: 180,
    parentId: 2,
    type: "menu",
    key: "system.settingsGroup",
    name: "系统设置",
    icon: "settings",
    order: 20,
  },
  {
    id: 190,
    parentId: 2,
    type: "menu",
    key: "system.audit",
    name: "审计与会话",
    icon: "operationLog",
    order: 50,
  },
  {
    id: 140,
    parentId: 0,
    type: "route",
    key: "profile",
    name: "个人中心",
    path: "/profile",
    icon: "profile",
    order: 30,
    hidden: 0,
  },
  {
    id: 141,
    parentId: 140,
    type: "action",
    key: "profile.query",
    name: "查看个人中心",
    order: 1,
    hidden: 0,
  },
  {
    id: 142,
    parentId: 140,
    type: "action",
    key: "profile.update",
    name: "更新个人资料",
    order: 2,
    hidden: 0,
  },
  ...moduleRules.flatMap((moduleItem) => {
    const route: SeedRule = {
      ...moduleItem.route,
      type: "route",
    };
    const actions: SeedRule[] = moduleItem.actions.map(([action, name], index) => ({
      id: moduleItem.route.id + index + 1,
      parentId: moduleItem.route.id,
      type: "action",
      key: `${moduleItem.route.key}.${action}`,
      name,
      order: index + 1,
      hidden: 0,
    }));
    return [route, ...actions];
  }),
];

export const seedDicts = [
  {
    id: 1,
    name: "状态",
    code: "status",
    items: [
      { label: "启用", value: "1", color: "green", sort: 1 },
      { label: "停用", value: "0", color: "red", sort: 2 },
    ],
  },
  {
    id: 2,
    name: "性别",
    code: "sex",
    items: [
      { label: "未知", value: "0", color: "default", sort: 1 },
      { label: "男", value: "1", color: "blue", sort: 2 },
      { label: "女", value: "2", color: "magenta", sort: 3 },
    ],
  },
  {
    id: 3,
    name: "菜单类型",
    code: "rule_type",
    items: [
      { label: "菜单项", value: "menu", color: "blue", sort: 1 },
      { label: "路由页面", value: "route", color: "green", sort: 2 },
      { label: "嵌套路由", value: "nested", color: "cyan", sort: 3 },
      { label: "权限项", value: "action", color: "orange", sort: 4 },
    ],
  },
  {
    id: 4,
    name: "数据范围",
    code: "data_scope",
    items: [
      { label: "全部数据", value: "all", color: "green", sort: 1 },
      { label: "指定部门", value: "custom_dept", color: "blue", sort: 2 },
      { label: "本部门", value: "current_dept", color: "cyan", sort: 3 },
      { label: "本部门及子部门", value: "current_dept_tree", color: "purple", sort: 4 },
      { label: "仅本人", value: "self", color: "orange", sort: 5 },
    ],
  },
  {
    id: 5,
    name: "存储类型",
    code: "storage_type",
    items: [
      { label: "本地存储", value: "local", color: "green", sort: 1 },
      { label: "S3-compatible", value: "s3", color: "blue", sort: 2 },
    ],
  },
];
